# Generated by Django 4.0 on 2022-11-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courtcaseproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientform',
            name='complaint',
            field=models.CharField(max_length=1000),
        ),
    ]
