# Generated by Django 4.0 on 2022-12-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courtcaseproject', '0002_alter_clientform_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientform',
            name='date',
            field=models.DateField(auto_created=True),
        ),
    ]
