# Generated by Django 4.0 on 2022-12-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courtcaseproject', '0003_alter_clientform_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientform',
            name='date',
            field=models.DateField(max_length=100),
        ),
    ]
